import React from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardFooter, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CheckCircle, Cube, Lightbulb, Rocket, Clock } from "lucide-react";

// Helper to parse GPT output
function parseGptOutput(gptText: string) {
  // Simple parser for the expected format
  const sections = gptText.split(/\n\s*##+ /g);
  let learningObjectives: string[] = [];
  let requiredMaterials: string[] = [];
  let steps: { title: string; hint: string }[] = [];

  for (const section of sections) {
    if (section.toLowerCase().startsWith("learning objectives")) {
      learningObjectives = section
        .split(/\n|\*/)
        .map((line) => line.replace(/^[\s\-*]+/, "").trim())
        .filter((line) => line && !line.toLowerCase().includes("learning objectives"));
    } else if (section.toLowerCase().startsWith("required materials")) {
      requiredMaterials = section
        .split(/\n|\*/)
        .map((line) => line.replace(/^[\s\-*]+/, "").trim())
        .filter((line) => line && !line.toLowerCase().includes("required materials"));
    } else if (section.toLowerCase().startsWith("step-by-step guidance")) {
      // Steps: 1. Title\n   - Subtext
      const stepLines = section.split(/\n/).filter(Boolean);
      let currentStep: { title: string; hint: string } = { title: "", hint: "" };
      for (const line of stepLines) {
        const stepMatch = line.match(/^\d+\.\s*(.*)/);
        if (stepMatch) {
          if (currentStep.title) steps.push(currentStep);
          currentStep = { title: stepMatch[1].trim(), hint: "" };
        } else if (line.trim().startsWith("*")) {
          currentStep.hint = line.replace(/^\*+/, "").trim();
        } else if (line.trim().startsWith("- ")) {
          currentStep.hint = line.replace(/^- /, "").trim();
        }
      }
      if (currentStep.title) steps.push(currentStep);
    }
  }
  return { learningObjectives, requiredMaterials, steps };
}

interface GptSuggestionCardProps {
  gptText: string;
}

const GptSuggestionCard: React.FC<GptSuggestionCardProps> = ({ gptText }) => {
  const { learningObjectives, requiredMaterials, steps } = parseGptOutput(gptText);

  return (
    <Card className="overflow-hidden shadow-lg bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 max-w-3xl mx-auto my-8">
      <div className="h-3 bg-gradient-to-r from-indigo-500 to-purple-600"></div>
      <CardHeader className="pb-2">
        <div className="flex items-center space-x-2 mb-2">
          <Rocket className="w-5 h-5 text-indigo-600" />
          <CardTitle className="text-2xl text-gray-900 dark:text-gray-100">AI Project Suggestions</CardTitle>
        </div>
        <CardDescription className="text-gray-600 dark:text-gray-400">
          Step-by-step guidance and resources generated by AI for your project.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          <div className="space-y-6 md:col-span-1">
            <div>
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">Learning Objectives</h3>
              <ul className="space-y-2">
                {learningObjectives.map((objective, idx) => (
                  <li key={idx} className="flex items-start">
                    <CheckCircle className="w-4 h-4 text-green-500 dark:text-green-400 mt-1 mr-2" />
                    <span className="text-gray-700 dark:text-gray-300">{objective}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">Required Materials</h3>
              <ul className="space-y-2">
                {requiredMaterials.map((material, idx) => (
                  <li key={idx} className="flex items-start">
                    <Cube className="w-4 h-4 text-indigo-500 dark:text-indigo-400 mt-1 mr-2" />
                    <span className="text-gray-700 dark:text-gray-300">{material}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <div className="md:col-span-2">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">Step-by-Step Guidance</h3>
            <div className="space-y-4">
              {steps.map((step, idx) => (
                <div
                  key={idx}
                  className="bg-gray-50 dark:bg-gray-700 p-4 rounded-lg border border-gray-200 dark:border-gray-600 transition-all duration-300"
                >
                  <div className="flex items-center mb-2">
                    <div className="bg-indigo-600 dark:bg-indigo-700 text-white w-6 h-6 rounded-full flex items-center justify-center mr-2 text-sm">
                      {idx + 1}
                    </div>
                    <h4 className="font-medium text-gray-900 dark:text-gray-100">{step.title}</h4>
                  </div>
                  <div className="pl-8">
                    <p className="text-gray-600 dark:text-gray-400 text-sm">
                      {step.hint || "Additional guidance for this step will appear here as you progress."}
                    </p>
                    <Button
                      variant="link"
                      className="text-indigo-600 dark:text-indigo-400 p-0 h-auto hover:text-indigo-800 dark:hover:text-indigo-300"
                    >
                      <Lightbulb className="w-3 h-3 mr-1" /> Get AI hint
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default GptSuggestionCard; 